# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://senspace.github.io/
date_format: "ordinal"
title: senspace
subtitle: "ğŸ­ğŸ‚ğŸ¯ğŸ°ğŸ²ğŸğŸğŸ‘ğŸµğŸ”ğŸ¶ğŸ–"
description: "Senspace's personal blog"
keywords: senspace, Fan
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Senspace
organization: Peking University, Inc.
organization_url: http://www.pku.edu.cn/
location: Beijing, China
email: notefan.j@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: é¦–é¡µ

  -
    href: /categories/
    label: åˆ†ç±»

  -
    href: /wiki/
    label: ç»´åŸº

  -
    href: /links/
    label: é“¾æ¥

  -
    href: /about/
    label: å…³äº

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: senspace
douban_username: senspace
facebook_username: senspace
weibo_username: senspace
zhihu_username: senspace
twitter_username: senspace

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!é‡è¦!!! è¯·ä¿®æ”¹ä¸‹é¢ä¸¤ä¸ªç”¨æˆ·åä¸ºä½ è‡ªå·±ç”³è¯·çš„
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: senspace
disqus_username: senspace
# åœ¨ä½¿ç”¨ disqus çš„æ—¶å€™å¯ç‚¹å‡»æ˜¾ç¤ºå¤šè¯´è¯„è®ºæ¡†
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C++, Python, Embedded System, Data Structure]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
